#!/usr/bin/env node
"use strict";

/**
 * Loopback auth gateway for CycloneAgentMCP.exe (stdio).
 * Public HTTPS is provided by cloudflared in front of this process.
 * Mutating phone tools never leave this host without a valid bearer token,
 * and are blocked entirely while GATEWAY_MODE=readonly.
 */

const http = require("http");
const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const { spawn } = require("child_process");

const ROOT = path.resolve(__dirname, "..");
const CONFIG_PATH = path.join(ROOT, "config", "gateway.env");
const EXAMPLE_PATH = path.join(ROOT, "config", "gateway.env.example");

const DEFAULT_ALLOWLIST = [
  "phone_status",
  "phone_observe",
  "phone_locate",
  "phone_screenshot",
  "phone_capabilities",
  "phone_devices",
  "phone_current_page",
  "phone_page_history",
  "phone_ui_search",
  "phone_inspect_element",
];

function defaultMcpCommand() {
  const local = process.env.LOCALAPPDATA || "C:\\Users\\Agent\\AppData\\Local";
  const one = path.join(local, "Cyclone One", "CycloneAgentMCP.exe");
  const companion = path.join(local, "Cyclone PC Companion", "CycloneAgentMCP.exe");
  if (fs.existsSync(one)) return one;
  if (fs.existsSync(companion)) return companion;
  return one;
}

const DEFAULT_MCP = defaultMcpCommand();

function loadDotEnv(filePath) {
  const out = {};
  if (!fs.existsSync(filePath)) return out;
  const text = fs.readFileSync(filePath, "utf8");
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

function writeEnvFile(filePath, values) {
  const lines = [
    "# Generated by cyclone MCP auth gateway. Do not commit.",
    `# updated ${new Date().toISOString()}`,
    `GATEWAY_BEARER_TOKEN=${values.GATEWAY_BEARER_TOKEN}`,
    `GATEWAY_HOST=${values.GATEWAY_HOST || "127.0.0.1"}`,
    `GATEWAY_PORT=${values.GATEWAY_PORT || "8787"}`,
    `GATEWAY_MODE=${values.GATEWAY_MODE || "readonly"}`,
  ];
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, lines.join("\n") + "\n", { encoding: "utf8", mode: 0o600 });
}

function envOr(fileMap, key, fallback) {
  if (process.env[key] != null && process.env[key] !== "") return process.env[key];
  if (fileMap[key] != null && fileMap[key] !== "") return fileMap[key];
  return fallback;
}

function parseAllowlist(raw) {
  if (!raw) return DEFAULT_ALLOWLIST.slice();
  return raw
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}

function ensureToken(fileMap) {
  let token = envOr(fileMap, "GATEWAY_BEARER_TOKEN", "");
  if (token && token !== "replace-me" && token.length >= 16) return token;
  token = crypto.randomBytes(32).toString("base64url");
  const next = {
    GATEWAY_BEARER_TOKEN: token,
    GATEWAY_HOST: envOr(fileMap, "GATEWAY_HOST", "127.0.0.1"),
    GATEWAY_PORT: envOr(fileMap, "GATEWAY_PORT", "8787"),
    GATEWAY_MODE: envOr(fileMap, "GATEWAY_MODE", "readonly"),
  };
  writeEnvFile(CONFIG_PATH, next);
  log("info", `wrote new bearer token to ${CONFIG_PATH}`);
  return token;
}

const fileMap = { ...loadDotEnv(EXAMPLE_PATH), ...loadDotEnv(CONFIG_PATH) };

const CONFIG = {
  host: envOr(fileMap, "GATEWAY_HOST", "127.0.0.1"),
  port: Number(envOr(fileMap, "GATEWAY_PORT", "8787")),
  token: ensureToken(fileMap),
  mode: String(envOr(fileMap, "GATEWAY_MODE", "readonly")).toLowerCase(),
  allowlist: parseAllowlist(envOr(fileMap, "GATEWAY_ALLOWLIST", "")),
  mcpCommand: envOr(fileMap, "MCP_COMMAND", DEFAULT_MCP),
  mcpArgs: envOr(fileMap, "MCP_ARGS", "serve").split(/\s+/).filter(Boolean),
  idleSec: Number(envOr(fileMap, "GATEWAY_SESSION_IDLE_SEC", "900")),
  maxSessions: Number(envOr(fileMap, "GATEWAY_MAX_SESSIONS", "8")),
  publicUrl: envOr(fileMap, "PUBLIC_URL", "").replace(/\/$/, ""),
  toolTimeoutMs: Number(envOr(fileMap, "GATEWAY_TOOL_TIMEOUT_MS", "120000")),
  initTimeoutMs: Number(envOr(fileMap, "GATEWAY_INIT_TIMEOUT_MS", "25000")),
};

const allowSet = new Set(CONFIG.allowlist);
const startedAt = Date.now();
const sessions = new Map();

const LOG_FILE =
  process.env.GATEWAY_LOG_FILE || path.join(ROOT, "artifacts", "runtime", "gateway.err");

function log(level, msg) {
  const line = `${new Date().toISOString()} [${level}] ${msg}`;
  process.stderr.write(line + "\n");
  try {
    fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });
    fs.appendFileSync(LOG_FILE, line + "\n");
  } catch {
    /* ignore disk errors */
  }
}

function tokenFingerprint(token) {
  return token.slice(-4);
}

function timingSafeEqualString(a, b) {
  const left = Buffer.from(String(a || ""), "utf8");
  const right = Buffer.from(String(b || ""), "utf8");
  if (left.length !== right.length) {
    crypto.timingSafeEqual(left, left);
    return false;
  }
  return crypto.timingSafeEqual(left, right);
}

function bearerFromReq(req) {
  const header = req.headers.authorization || req.headers.Authorization || "";
  const m = String(header).match(/^Bearer\s+(.+)$/i);
  if (m) return m[1].trim();
  // Cloudflare Access is an alternative *in addition to* never skipping mutating
  // tools without a bearer. Access-only is accepted only when explicitly enabled.
  return "";
}

function isAuthorized(req) {
  const presented = bearerFromReq(req);
  if (presented && timingSafeEqualString(presented, CONFIG.token)) return true;
  // Cloudflare Access may substitute for bearer only in readonly mode.
  // Mutating tools (GATEWAY_MODE=full) always require the bearer token.
  if (CONFIG.mode !== "readonly") return false;
  const acceptCf = String(envOr(fileMap, "GATEWAY_ACCEPT_CF_ACCESS", "")).toLowerCase();
  if (acceptCf === "1" || acceptCf === "true") {
    const jwt = req.headers["cf-access-jwt-assertion"];
    const email = req.headers["cf-access-authenticated-user-email"];
    if (jwt && email) return true;
  }
  return false;
}

function allowedOrigin(origin) {
  if (!origin) return true;
  let url;
  try {
    url = new URL(origin);
  } catch {
    return false;
  }
  const host = url.hostname.toLowerCase();
  if (host === "127.0.0.1" || host === "localhost") return true;
  if (host.endsWith(".trycloudflare.com") || host.endsWith(".cfargotunnel.com")) return true;
  if (CONFIG.publicUrl) {
    try {
      if (new URL(CONFIG.publicUrl).hostname.toLowerCase() === host) return true;
    } catch {
      /* ignore */
    }
  }
  const extra = envOr(fileMap, "GATEWAY_ORIGIN_ALLOW", "");
  if (extra) {
    for (const item of extra.split(",")) {
      const n = item.trim().toLowerCase();
      if (!n) continue;
      if (origin.toLowerCase() === n || host === n) return true;
    }
  }
  return false;
}

function setCors(req, res) {
  const origin = req.headers.origin;
  if (origin && allowedOrigin(origin)) {
    res.setHeader("Access-Control-Allow-Origin", origin);
    res.setHeader("Vary", "Origin");
    res.setHeader("Access-Control-Allow-Headers", "Authorization, Content-Type, Accept, Mcp-Session-Id, MCP-Protocol-Version, Last-Event-ID");
    res.setHeader("Access-Control-Allow-Methods", "GET, POST, DELETE, OPTIONS");
    res.setHeader("Access-Control-Expose-Headers", "Mcp-Session-Id, WWW-Authenticate");
  }
}

function sendJson(req, res, status, body, extraHeaders) {
  setCors(req, res);
  const payload = JSON.stringify(body);
  res.writeHead(status, {
    "Content-Type": "application/json; charset=utf-8",
    "Cache-Control": "no-store",
    ...(extraHeaders || {}),
  });
  res.end(payload);
}

function sendUnauthorized(req, res) {
  const resource = (CONFIG.publicUrl || `http://${CONFIG.host}:${CONFIG.port}`) + "/mcp";
  sendJson(
    req,
    res,
    401,
    { error: "unauthorized", message: "Authorization: Bearer <token> required" },
    {
      "WWW-Authenticate": `Bearer realm="cyclone-mcp", error="invalid_token", resource_metadata="${resource.replace(/\/mcp$/, "")}/.well-known/oauth-protected-resource"`,
    }
  );
}

function jsonRpcError(id, code, message) {
  return { jsonrpc: "2.0", id: id ?? null, error: { code, message } };
}

function isJsonRpcRequest(msg) {
  return msg && typeof msg === "object" && !Array.isArray(msg) && typeof msg.method === "string" && Object.prototype.hasOwnProperty.call(msg, "id");
}

function isJsonRpcNotification(msg) {
  return msg && typeof msg === "object" && !Array.isArray(msg) && typeof msg.method === "string" && !Object.prototype.hasOwnProperty.call(msg, "id");
}

function toolNameFromCall(msg) {
  if (!msg || msg.method !== "tools/call") return "";
  const params = msg.params || {};
  return String(params.name || params.tool || "");
}

function blockedByAllowlist(msg) {
  if (CONFIG.mode !== "readonly") return null;
  if (!msg || msg.method !== "tools/call") return null;
  const name = toolNameFromCall(msg);
  if (!name) return "tools/call missing tool name";
  if (!allowSet.has(name)) {
    return `Tool '${name}' is blocked by gateway readonly allowlist`;
  }
  return null;
}

function filterReadonlyPayload(msg) {
  if (CONFIG.mode !== "readonly") return msg;
  if (!msg || !msg.result || typeof msg.result !== "object") return msg;
  const result = { ...msg.result };
  if (Array.isArray(result.tools)) {
    result.tools = result.tools.filter((t) => t && allowSet.has(t.name));
  }
  if (typeof result.instructions === "string") {
    result.instructions =
      "Read-only Cyclone phone MCP (gateway allowlist). Use phone_status, phone_observe, phone_locate, phone_screenshot, phone_capabilities, phone_devices. Mutating tools such as phone_act are not available on this endpoint.";
  }
  return { ...msg, result };
}

class StdioSession {
  constructor(id) {
    this.id = id;
    this.pending = new Map();
    this.notifyQueue = [];
    this.sseClients = new Set();
    this.buffer = "";
    this.alive = true;
    this.lastUsed = Date.now();
    this.child = spawn(CONFIG.mcpCommand, CONFIG.mcpArgs, {
      stdio: ["pipe", "pipe", "pipe"],
      windowsHide: true,
      env: process.env,
    });
    this.child.stdout.setEncoding("utf8");
    this.child.stderr.setEncoding("utf8");
    this.child.stdout.on("data", (chunk) => this._onStdout(chunk));
    this.child.stderr.on("data", (chunk) => {
      const text = String(chunk).trim();
      if (text) log("mcp", `[${this.id.slice(0, 8)}] ${text}`);
    });
    this.child.on("exit", (code, signal) => {
      this.alive = false;
      log("info", `mcp child exit session=${this.id.slice(0, 8)} code=${code} signal=${signal}`);
      for (const [, waiter] of this.pending) {
        waiter.reject(new Error("MCP child exited"));
      }
      this.pending.clear();
    });
    this.child.on("error", (err) => {
      this.alive = false;
      log("error", `mcp spawn error: ${err.message}`);
    });
  }

  _onStdout(chunk) {
    this.buffer += chunk;
    for (;;) {
      const nl = this.buffer.indexOf("\n");
      if (nl < 0) break;
      const line = this.buffer.slice(0, nl).trim();
      this.buffer = this.buffer.slice(nl + 1);
      if (!line) continue;
      let msg;
      try {
        msg = JSON.parse(line);
      } catch (err) {
        log("warn", `bad mcp json: ${err.message}`);
        continue;
      }
      this._dispatch(msg);
    }
  }

  _dispatch(msg) {
    if (Array.isArray(msg)) {
      for (const item of msg) this._dispatch(item);
      return;
    }
    if (msg && Object.prototype.hasOwnProperty.call(msg, "id") && this.pending.has(msg.id)) {
      const waiter = this.pending.get(msg.id);
      this.pending.delete(msg.id);
      waiter.resolve(filterReadonlyPayload(msg));
      return;
    }
    this._emitSse(msg);
  }

  _emitSse(msg) {
    const data = `event: message\ndata: ${JSON.stringify(msg)}\n\n`;
    for (const res of this.sseClients) {
      try {
        res.write(data);
      } catch {
        this.sseClients.delete(res);
      }
    }
    if (this.sseClients.size === 0) {
      this.notifyQueue.push(msg);
      if (this.notifyQueue.length > 50) this.notifyQueue.shift();
    }
  }

  send(msg, timeoutMs) {
    this.lastUsed = Date.now();
    if (!this.alive) return Promise.reject(new Error("session dead"));
    const line = JSON.stringify(msg) + "\n";
    if (!this.child.stdin.writable) return Promise.reject(new Error("mcp stdin closed"));
    this.child.stdin.write(line);
    if (!isJsonRpcRequest(msg)) return Promise.resolve(null);
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        this.pending.delete(msg.id);
        reject(new Error("mcp timeout"));
      }, timeoutMs);
      this.pending.set(msg.id, {
        resolve: (value) => {
          clearTimeout(timer);
          resolve(value);
        },
        reject: (err) => {
          clearTimeout(timer);
          reject(err);
        },
      });
    });
  }

  attachSse(res) {
    this.sseClients.add(res);
    for (const msg of this.notifyQueue) {
      res.write(`event: message\ndata: ${JSON.stringify(msg)}\n\n`);
    }
    this.notifyQueue = [];
    res.on("close", () => this.sseClients.delete(res));
  }

  destroy() {
    this.alive = false;
    for (const [, waiter] of this.pending) waiter.reject(new Error("session closed"));
    this.pending.clear();
    for (const res of this.sseClients) {
      try {
        res.end();
      } catch {
        /* ignore */
      }
    }
    this.sseClients.clear();
    try {
      if (this.child && !this.child.killed) this.child.kill();
    } catch {
      /* ignore */
    }
  }
}

function reapIdle() {
  if (!CONFIG.idleSec) return;
  const cutoff = Date.now() - CONFIG.idleSec * 1000;
  for (const [id, session] of sessions) {
    if (session.lastUsed < cutoff) {
      log("info", `reap idle session ${id.slice(0, 8)}`);
      session.destroy();
      sessions.delete(id);
    }
  }
}
setInterval(reapIdle, 30000).unref();

function newSession() {
  if (sessions.size >= CONFIG.maxSessions) {
    const oldest = [...sessions.values()].sort((a, b) => a.lastUsed - b.lastUsed)[0];
    if (oldest) {
      log("info", `evict session ${oldest.id.slice(0, 8)} (max ${CONFIG.maxSessions})`);
      oldest.destroy();
      sessions.delete(oldest.id);
    }
  }
  const id = crypto.randomBytes(16).toString("hex");
  const session = new StdioSession(id);
  sessions.set(id, session);
  return session;
}

function readBody(req, limit) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    let size = 0;
    req.on("data", (c) => {
      size += c.length;
      if (size > limit) {
        reject(Object.assign(new Error("payload too large"), { statusCode: 413 }));
        req.destroy();
        return;
      }
      chunks.push(c);
    });
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
}

function healthBody() {
  const binaryOk = fs.existsSync(CONFIG.mcpCommand);
  return {
    ok: true,
    service: "cyclone-mcp-auth-gateway",
    mode: CONFIG.mode,
    allowlist: CONFIG.mode === "readonly" ? CONFIG.allowlist : "all",
    mcpBinary: binaryOk,
    mcpCommand: CONFIG.mcpCommand,
    sessions: sessions.size,
    uptimeSec: Math.round((Date.now() - startedAt) / 1000),
    bind: `${CONFIG.host}:${CONFIG.port}`,
    auth: "Authorization: Bearer",
    endpoints: {
      health: "/health",
      mcp: "/mcp",
      sseLegacy: "/sse",
    },
  };
}

function wellKnown(req) {
  const origin = CONFIG.publicUrl || `http://${CONFIG.host}:${CONFIG.port}`;
  return {
    resource: origin + "/mcp",
    bearer_methods_supported: ["header"],
    resource_documentation: "Cyclone MCP auth gateway. Use Authorization: Bearer <token>. No OAuth authorization server is published on this host.",
  };
}

async function handleMcpPost(req, res, sessionIdHint) {
  let raw;
  try {
    raw = await readBody(req, 10 * 1024 * 1024);
  } catch (err) {
    sendJson(req, res, err.statusCode || 400, { error: err.message });
    return;
  }
  if (!raw) {
    sendJson(req, res, 400, { error: "empty body" });
    return;
  }
  let payload;
  try {
    payload = JSON.parse(raw);
  } catch {
    sendJson(req, res, 400, { error: "invalid json" });
    return;
  }

  const messages = Array.isArray(payload) ? payload : [payload];
  const hasRequest = messages.some(isJsonRpcRequest);
  const isInit = messages.some((m) => m && m.method === "initialize");

  let session = sessionIdHint ? sessions.get(sessionIdHint) : null;
  if (isInit) {
    if (session) {
      session.destroy();
      sessions.delete(session.id);
    }
    session = newSession();
  } else if (!session) {
    if (sessionIdHint) {
      sendJson(req, res, 404, { error: "unknown session" });
      return;
    }
    session = newSession();
  }

  if (!session.alive) {
    sendJson(req, res, 503, { error: "mcp child not running" });
    return;
  }

  const replies = [];
  for (const msg of messages) {
    if (isJsonRpcRequest(msg)) {
      const blocked = blockedByAllowlist(msg);
      if (blocked) {
        log("info", `blocked ${toolNameFromCall(msg)} session=${session.id.slice(0, 8)}`);
        replies.push(jsonRpcError(msg.id, -32001, blocked));
        continue;
      }
    }
    const timeout = msg && msg.method === "initialize" ? CONFIG.initTimeoutMs : CONFIG.toolTimeoutMs;
    try {
      const reply = await session.send(msg, timeout);
      if (reply) replies.push(reply);
    } catch (err) {
      if (isJsonRpcRequest(msg)) {
        replies.push(jsonRpcError(msg.id, -32000, err.message));
      }
    }
  }

  const headers = {
    "Mcp-Session-Id": session.id,
    "Cache-Control": "no-store",
  };

  if (!hasRequest) {
    setCors(req, res);
    res.writeHead(202, headers);
    res.end();
    return;
  }

  const body = Array.isArray(payload) ? replies : replies[0] ?? jsonRpcError(null, -32603, "no response");
  setCors(req, res);
  res.writeHead(200, { ...headers, "Content-Type": "application/json; charset=utf-8" });
  res.end(JSON.stringify(body));
}

function handleMcpGet(req, res, session) {
  setCors(req, res);
  res.writeHead(200, {
    "Content-Type": "text/event-stream; charset=utf-8",
    "Cache-Control": "no-cache, no-transform",
    Connection: "keep-alive",
    "Mcp-Session-Id": session.id,
  });
  res.write(": connected\n\n");
  session.attachSse(res);
  const ping = setInterval(() => {
    try {
      res.write(": ping\n\n");
    } catch {
      clearInterval(ping);
    }
  }, 15000);
  res.on("close", () => clearInterval(ping));
}

function handleLegacySse(req, res, session) {
  setCors(req, res);
  res.writeHead(200, {
    "Content-Type": "text/event-stream; charset=utf-8",
    "Cache-Control": "no-cache, no-transform",
    Connection: "keep-alive",
  });
  res.write(`event: endpoint\ndata: /messages?sessionId=${session.id}\n\n`);
  session.attachSse(res);
  const ping = setInterval(() => {
    try {
      res.write(": ping\n\n");
    } catch {
      clearInterval(ping);
    }
  }, 15000);
  res.on("close", () => clearInterval(ping));
}

function pathnameOf(req) {
  try {
    return new URL(req.url, `http://${CONFIG.host}:${CONFIG.port}`).pathname.replace(/\/+$/, "") || "/";
  } catch {
    return "/";
  }
}

function queryOf(req) {
  try {
    return new URL(req.url, `http://${CONFIG.host}:${CONFIG.port}`).searchParams;
  } catch {
    return new URLSearchParams();
  }
}

const server = http.createServer(async (req, res) => {
  const origin = req.headers.origin;
  if (origin && !allowedOrigin(origin)) {
    sendJson(req, res, 403, { error: "origin not allowed" });
    return;
  }

  if (req.method === "OPTIONS") {
    setCors(req, res);
    res.writeHead(204);
    res.end();
    return;
  }

  const pathname = pathnameOf(req);
  const q = queryOf(req);

  if ((pathname === "/health" || pathname === "/healthz") && req.method === "GET") {
    sendJson(req, res, 200, healthBody());
    return;
  }

  if (pathname === "/" && req.method === "GET") {
    sendJson(req, res, 200, {
      service: "cyclone-mcp-auth-gateway",
      health: "/health",
      mcp: "/mcp",
      auth: "Authorization: Bearer required for /mcp",
    });
    return;
  }

  if (pathname === "/.well-known/oauth-protected-resource") {
    sendJson(req, res, 200, wellKnown(req));
    return;
  }

  const mcpPaths = pathname === "/mcp" || pathname === "/sse" || pathname === "/messages";
  if (!mcpPaths) {
    sendJson(req, res, 404, { error: "not found" });
    return;
  }

  if (!isAuthorized(req)) {
    sendUnauthorized(req, res);
    return;
  }

  const sessionHeader = req.headers["mcp-session-id"] || q.get("sessionId") || "";

  try {
    if (pathname === "/mcp" && req.method === "POST") {
      await handleMcpPost(req, res, sessionHeader);
      return;
    }
    if (pathname === "/mcp" && req.method === "GET") {
      const session = sessionHeader ? sessions.get(sessionHeader) : newSession();
      if (!session) {
        sendJson(req, res, 404, { error: "unknown session" });
        return;
      }
      handleMcpGet(req, res, session);
      return;
    }
    if (pathname === "/mcp" && req.method === "DELETE") {
      const session = sessions.get(sessionHeader);
      if (session) {
        session.destroy();
        sessions.delete(session.id);
      }
      setCors(req, res);
      res.writeHead(204);
      res.end();
      return;
    }
    if (pathname === "/sse" && req.method === "GET") {
      const session = newSession();
      handleLegacySse(req, res, session);
      return;
    }
    if (pathname === "/messages" && req.method === "POST") {
      await handleMcpPost(req, res, sessionHeader);
      return;
    }
    sendJson(req, res, 405, { error: "method not allowed" });
  } catch (err) {
    log("error", err.stack || err.message);
    if (!res.headersSent) sendJson(req, res, 500, { error: "gateway error" });
  }
});

function shutdown(signal) {
  log("info", `shutdown ${signal}`);
  for (const session of sessions.values()) session.destroy();
  sessions.clear();
  server.close(() => process.exit(0));
  setTimeout(() => process.exit(0), 2000).unref();
}

process.on("SIGINT", () => shutdown("SIGINT"));
process.on("SIGTERM", () => shutdown("SIGTERM"));

if (CONFIG.host !== "127.0.0.1" && CONFIG.host !== "localhost") {
  log("error", `refusing to bind ${CONFIG.host}; gateway must stay on loopback`);
  process.exit(2);
}

if (!fs.existsSync(CONFIG.mcpCommand)) {
  log("error", `MCP binary missing: ${CONFIG.mcpCommand}`);
  process.exit(2);
}

if (CONFIG.mode !== "readonly" && CONFIG.mode !== "full") {
  log("error", `invalid GATEWAY_MODE=${CONFIG.mode}`);
  process.exit(2);
}

server.listen(CONFIG.port, CONFIG.host, () => {
  log(
    "info",
    `listening http://${CONFIG.host}:${CONFIG.port} mode=${CONFIG.mode} token=...${tokenFingerprint(CONFIG.token)} mcp=${CONFIG.mcpCommand}`
  );
  if (CONFIG.mode === "full") {
    log("warn", "GATEWAY_MODE=full exposes mutating phone tools to any client with the bearer token");
  }
});
