package com.cyclone.teamworksniper.runtime

import android.accessibilityservice.AccessibilityService
import android.os.SystemClock
import android.view.accessibility.AccessibilityEvent
import android.view.accessibility.AccessibilityNodeInfo
import com.cyclone.teamworksniper.data.*
import com.cyclone.teamworksniper.rules.*
import com.cyclone.teamworksniper.teamwork.TeamworkParser
import java.time.LocalDate
import java.util.UUID
import java.util.concurrent.atomic.AtomicBoolean
import kotlinx.coroutines.*

class TeamworkAccessibilityService:AccessibilityService(){
    private val job=SupervisorJob();private val scope=CoroutineScope(job+Dispatchers.Main.immediate);private val busy=AtomicBoolean(false);private var queued:TriggerEvent?=null
    private val rules by lazy{RuleStore(this)};private val settings by lazy{SettingsStore(this)};private val log by lazy{ActivityLogStore(this)}
    override fun onServiceConnected(){super.onServiceConnected();SniperCoordinator.attach(this)};override fun onDestroy(){SniperCoordinator.detach(this);job.cancel();super.onDestroy()};override fun onInterrupt()=Unit
    override fun onAccessibilityEvent(event:AccessibilityEvent?){if(event?.packageName?.toString()!=TeamworkLauncher.PACKAGE)return;SniperCoordinator.current()?.let(::requestEvaluation)}
    fun requestEvaluation(trigger:TriggerEvent){if(!busy.compareAndSet(false,true)){queued=trigger;return};scope.launch{try{evaluate(trigger)}finally{SniperCoordinator.consume(trigger);busy.set(false);queued?.also{queued=null;requestEvaluation(it)}}}}
    private suspend fun evaluate(trigger:TriggerEvent){val started=SystemClock.elapsedRealtime();val root=awaitRoot();if(root==null){record(trigger,"NO_ACTION",emptyList(),emptyList(),false,null,null,"Teamwork accessibility root unavailable; launch=${trigger.launchOutcome}",null,null);return};val openLatency=SystemClock.elapsedRealtime()-trigger.elapsedRealtimeMs;val parser=TeamworkParser(LocalDate.now());val quick=try{parser.parse(AccessibilitySemanticTree.snapshot(root)).shifts.map{it.shift}}finally{root.recycle()};val currentRules=rules.load();RuleEngine(LocalDate.now()).evaluate(currentRules,quick);val compareLatency=SystemClock.elapsedRealtime()-trigger.elapsedRealtimeMs;val all=scan(parser,false);val evaluation=RuleEngine(LocalDate.now()).evaluate(currentRules,all);val mode=SafetyGate.decide(settings.load(),evaluation);var attempted=false;var result:String?=null;var verify:String?=null;var failure:String?=null;var claimDuration:Long?=null;if(mode==ExecutionMode.CLAIM){attempted=true;val cs=SystemClock.elapsedRealtime();val o=execute(evaluation.matches,currentRules,parser);claimDuration=SystemClock.elapsedRealtime()-cs;result=o.first;verify=o.second;failure=o.third};record(trigger,when(mode){ExecutionMode.NO_ACTION->if(evaluation.matches.isEmpty())"MISS" else "DISABLED";ExecutionMode.DRY_RUN->"WOULD_CLAIM";ExecutionMode.CLAIM->"CLAIM_FLOW"},all,evaluation.evaluatedRuleIds,attempted,result,verify,failure,openLatency,compareLatency,SystemClock.elapsedRealtime()-started,claimDuration)}
    private suspend fun awaitRoot():AccessibilityNodeInfo?{repeat(12){val r=rootInActiveWindow;if(r!=null){if(r.packageName?.toString()==TeamworkLauncher.PACKAGE)return r;r.recycle()};delay(100)};return null}
    private suspend fun scan(parser:TeamworkParser,reset:Boolean):List<OpenShift>{if(reset)rewind();val states=mutableSetOf<String>();val shifts=linkedMapOf<String,OpenShift>();var noNew=0;repeat(16){val r=rootInActiveWindow?:return@repeat;if(r.packageName?.toString()!=TeamworkLauncher.PACKAGE){r.recycle();return shifts.values.toList()};val snap=try{AccessibilitySemanticTree.snapshot(r)}finally{r.recycle()};val state=snap.subtreeSemanticText().replace(Regex("\\s+")," ").trim().lowercase().take(5000);if(!states.add(state))return shifts.values.toList();val before=shifts.size;parser.parse(snap).shifts.map{it.shift}.forEach{shifts.putIfAbsent(it.stableKey,it)};noNew=if(shifts.size==before)noNew+1 else 0;if(noNew>=2||!scroll(AccessibilityNodeInfo.ACTION_SCROLL_FORWARD))return shifts.values.toList();delay(90)};return shifts.values.toList()}
    private suspend fun rewind(){val states=mutableSetOf<String>();repeat(16){val r=rootInActiveWindow?:return;val state=try{AccessibilitySemanticTree.snapshot(r).subtreeSemanticText().replace(Regex("\\s+")," ").trim().lowercase().take(5000)}finally{r.recycle()};if(!states.add(state)||!scroll(AccessibilityNodeInfo.ACTION_SCROLL_BACKWARD))return;delay(90)}}
    private fun scroll(action:Int):Boolean{val r=rootInActiveWindow?:return false;return try{val n=AccessibilitySemanticTree.firstScrollable(r,action)?:return false;try{n.performAction(action)}finally{n.recycle()}}finally{r.recycle()}}
    private suspend fun execute(matches:List<RuleMatch>,evaluatedRules:List<ShiftRule>,parser:TeamworkParser):Triple<String,String,String?>{val byId=evaluatedRules.associateBy{it.id};val done=mutableSetOf<String>();val results=mutableListOf<String>();for(match in matches.sortedBy{it.date}){val rule=byId[match.ruleId]?:continue;val current=rules.load().firstOrNull{it.id==rule.id&&it.enabled};if(current!=rule)return Triple(results.joinToString(";"),"STOPPED","Rule changed before claim");if(!settings.load().let{it.enabled&&it.armed})return Triple(results.joinToString(";"),"STOPPED","Sniper not both enabled and armed");val preflight=RuleEngine(LocalDate.now()).evaluate(listOf(rule),scan(parser,true)).matches.firstOrNull{it.date==match.date}?:return Triple(results.joinToString(";"),"STOPPED","Rule no longer fully matches");if(rule.type==RuleType.SEQUENCE&&preflight.shifts.map{it.code}!=match.shifts.map{it.code})return Triple(results.joinToString(";"),"STOPPED","Sequence changed before action");for(target in match.shifts){if(target.stableKey in done)continue;if(rule.type==RuleType.SEQUENCE){val remaining=match.shifts.filter{it.stableKey !in done}.map{it.code}.toSet();val fresh=scan(parser,true).filter{it.date==match.date&&it.code in remaining}.map{it.code}.toSet();if(!fresh.containsAll(remaining))return Triple(results.joinToString(";"),"PARTIAL_STOP","Sequence member disappeared")};val o=clickFresh(target,rule,parser);results+="${target.date} ${target.code}:${o.first}";if(!o.second)return Triple(results.joinToString(";"),o.third,o.fourth);done+=target.stableKey}};return Triple(results.ifEmpty{listOf("NO_UNIQUE_TARGET")}.joinToString(";"),if(done.isEmpty())"NOT_EXECUTED" else "VERIFIED_NOT_OPEN_AFTER_ACTION",null)}
    private suspend fun clickFresh(target:OpenShift,rule:ShiftRule,parser:TeamworkParser):Quad{if(!rules.load().any{it==rule&&it.enabled}||!settings.load().let{it.enabled&&it.armed})return Quad("NOT_EXECUTED",false,"STOPPED","Safety state changed");rewind();val states=mutableSetOf<String>();repeat(16){val r=rootInActiveWindow?:return@repeat;if(r.packageName?.toString()!=TeamworkLauncher.PACKAGE){r.recycle();return Quad("NOT_EXECUTED",false,"STOPPED","Teamwork not active")};val snap=AccessibilitySemanticTree.snapshot(r);val state=snap.subtreeSemanticText().replace(Regex("\\s+")," ").trim().lowercase().take(5000);if(!states.add(state)){r.recycle();return Quad("NOT_EXECUTED",false,"STOPPED","Target not found")};val candidates=parser.parse(snap).shifts.filter{same(it.shift,target)};if(candidates.size>1){r.recycle();return Quad("NOT_EXECUTED",false,"AMBIGUOUS","Multiple fresh semantic candidates")};if(candidates.size==1){val row=AccessibilitySemanticTree.nodeAtPath(r,candidates.single().observationPath);r.recycle();if(row==null)return Quad("NOT_EXECUTED",false,"STALE","Fresh semantic path disappeared");val click=try{AccessibilitySemanticTree.nearestClickable(row)}finally{row.recycle()}?:return Quad("NOT_EXECUTED",false,"NO_ACTION","No clickable semantic node or ancestor");val sent=try{click.performAction(AccessibilityNodeInfo.ACTION_CLICK)}finally{click.recycle()};if(!sent)return Quad("CLICK_REJECTED",false,"FAILED","ACTION_CLICK returned false");delay(140);val confirm=maybeConfirm(target);if(confirm)delay(140);val post=awaitRoot()?:return Quad("ACTION_SENT",false,"UNVERIFIED","Teamwork root unavailable after action");val text=try{AccessibilitySemanticTree.snapshot(post).subtreeSemanticText()}finally{post.recycle()};val success=Regex("(?i)\\b(claimed|shift taken|added to (your )?schedule|you have this shift)\\b").containsMatchIn(text);if(!confirm&&!success)return Quad("ROW_ACTION_SENT",false,"UNVERIFIED","No bound confirmation or explicit success evidence");val still=scan(parser,true).any{same(it,target)};return if(!still)Quad(if(confirm)"CONFIRMED_ACTION_SENT" else "DIRECT_ACTION_SENT",true,"TARGET_NO_LONGER_OPEN",null)else Quad("ACTION_SENT",false,"FAILED","Target still Open to take")};r.recycle();if(!scroll(AccessibilityNodeInfo.ACTION_SCROLL_FORWARD))return Quad("NOT_EXECUTED",false,"STOPPED","Target no longer present");delay(90)};return Quad("NOT_EXECUTED",false,"STOPPED","Bounded fresh scan exhausted")}
    private fun maybeConfirm(target:OpenShift):Boolean{val r=rootInActiveWindow?:return false;return try{if(r.packageName?.toString()!=TeamworkLauncher.PACKAGE)return false;val b=AccessibilitySemanticTree.findClickableByOwnText(r){Regex("(?i)^(confirm|take shift|claim shift|take)$").matches(it.trim())}?:return false;val belongs=ancestorMentions(b,target);if(!belongs){b.recycle();return false};try{b.performAction(AccessibilityNodeInfo.ACTION_CLICK)}finally{b.recycle()}}finally{r.recycle()}}
    private fun ancestorMentions(button:AccessibilityNodeInfo,target:OpenShift):Boolean{var c:AccessibilityNodeInfo?=AccessibilityNodeInfo.obtain(button);repeat(5){val n=c?:return false;val text=AccessibilitySemanticTree.snapshot(n).subtreeSemanticText();val ok=Regex("(?i)(?<![A-Z0-9])${target.code.name}(?![A-Z0-9])").containsMatchIn(text)&&(target.startTime?.let{t->text.contains("${t.hour}:${"%02d".format(t.minute)}")||text.contains("${t.hour}.${"%02d".format(t.minute)}")}?:true);if(ok){n.recycle();return true};val p=n.parent;n.recycle();c=p};c?.recycle();return false}
    private fun same(a:OpenShift,b:OpenShift)=a.date==b.date&&a.code==b.code&&a.startTime==b.startTime&&a.endTime==b.endTime
    private fun record(t:TriggerEvent,decision:String,shifts:List<OpenShift>,evaluated:List<String>,attempted:Boolean,result:String?,verify:String?,failure:String?,open:Long?=null,compare:Long?=null,evaluation:Long?=null,claim:Long?=null){val s=settings.load();log.append(ActivityEntry(UUID.randomUUID().toString(),t.source,t.wallClockEpochMs,t.notificationTitle,t.notificationText,open,compare,evaluation,claim,shifts.map{"${it.date} ${it.code}${it.startTime?.let{x->" $x"}?:""}"},evaluated,decision,s.armed,attempted,result,verify,failure))}
    private data class Quad(val first:String,val second:Boolean,val third:String,val fourth:String?)}
