"""The Cyclone mark (brand/logo-wormhole) is the one logo on every surface: the phone's launcher icon (colour, with a
themed one-colour layer), the in-app mark (colour), notifications, Quick Settings tiles and the overlay (one colour),
Glass's switcher and favicon (colour), and the Windows runtime and setup (colour icon)."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
RES = ROOT / "apps/mobile/app/src/main/res"
GENERATED = "Generated by brand/logo-wormhole/src/android.py"


def test_the_phone_has_an_adaptive_launcher_icon_with_a_themed_layer():
    manifest = (ROOT / "apps/mobile/app/src/main/AndroidManifest.xml").read_text(encoding="utf-8")
    assert 'android:icon="@mipmap/ic_launcher"' in manifest and 'android:roundIcon="@mipmap/ic_launcher_round"' in manifest
    for name in ("ic_launcher.xml", "ic_launcher_round.xml"):
        icon = (RES / "mipmap-anydpi" / name).read_text(encoding="utf-8")
        for layer in ("ic_launcher_background", "ic_launcher_foreground", "ic_launcher_monochrome"):
            assert f"@drawable/{layer}" in icon, (name, layer)


def test_every_android_mark_comes_from_the_brand_geometry():
    for name in ("ic_cyclone_mark_42", "ic_cyclone_status", "ic_launcher_foreground", "ic_launcher_monochrome", "ic_launcher_background"):
        assert GENERATED in (RES / "drawable" / f"{name}.xml").read_text(encoding="utf-8"), name
    # Status, tile and notification icons must stay one colour (Android uses only their alpha).
    status = (RES / "drawable/ic_cyclone_status.xml").read_text(encoding="utf-8")
    assert "gradient" not in status and 'android:fillColor="#FFFFFFFF"' in status


def test_glass_and_windows_use_the_same_mark():
    logos = (ROOT / "apps/glass/src/ui/logos.ts").read_text(encoding="utf-8")
    assert "CYCLONE_PETALS" in logos and "M101 45A43 43 0 0 0 31 27" not in logos  # the old three arcs are gone
    assert "Generated by" not in logos and (ROOT / "apps/glass/src/ui/cycloneMark.ts").exists()
    assert "%235b5bd6" not in (ROOT / "apps/glass/index.html").read_text(encoding="utf-8")  # the old indigo favicon
    assert (ROOT / "packaging/pc/cyclone.ico").stat().st_size > 1000
    assert 'Icon "cyclone.ico"' in (ROOT / "packaging/pc/cyclone-setup.nsi").read_text(encoding="utf-8")
    assert '"cyclone.ico"' in (ROOT / "packaging/pc-companion/pyinstaller/CyclonePCRuntime.spec").read_text(encoding="utf-8")
