"""Remote MCP tunnel (ChatGPT / Grok chat connectors): the same PowerShell pack Cyclone One ran, now driven by the
gateway for Glass. The pack lives in `%LOCALAPPDATA%\\Cyclone One\\mcp-tunnel`. The bearer is shown only when the owner
asks for it and never logged. `~/.grok/config.toml` is never touched."""
from __future__ import annotations

import os
import shutil
from pathlib import Path
from typing import Any, Callable

from ..tooling_seam import resolve_one_mcp_executable
from .common import PcFeatureError, Runner, install_root, is_windows, powershell_argv, resources_dir, run_process, script_json

BUNDLE_VERSION = "1.1.0-mcp-tunnel.1"
LOCAL_MCP_URL = "http://127.0.0.1:8787/mcp"
LOCAL_HEALTH_URL = "http://127.0.0.1:8787/health"
MODES = ("readonly", "full")
SKIP_ON_COPY = {"gateway.env", "artifacts", "runtime"}


def load_dot_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return values
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def set_env_key(path: Path, key: str, value: str) -> None:
    lines = path.read_text(encoding="utf-8").splitlines() if path.is_file() else []
    found = False
    for index, line in enumerate(lines):
        if line.startswith(f"{key}="):
            lines[index] = f"{key}={value}"
            found = True
    if not found:
        if not lines:
            lines = ["# Generated by Cyclone. Do not commit.", "GATEWAY_HOST=127.0.0.1", "GATEWAY_PORT=8787"]
        lines.append(f"{key}={value}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    protect_env_file(path)


def _copy_pack(src: Path, dest: Path) -> None:
    """Copy the bundled pack, never over the owner's secrets (gateway.env) or runtime state."""
    dest.mkdir(parents=True, exist_ok=True)
    for entry in src.iterdir():
        if entry.name.lower() in SKIP_ON_COPY:
            continue
        target = dest / entry.name
        if entry.is_dir():
            _copy_pack(entry, target)
        else:
            shutil.copy2(entry, target)


class TunnelService:
    def __init__(self, root: Path | None = None, pack: Path | None = None, run: Runner = run_process,
                 windows: Callable[[], bool] = is_windows, mcp_binary: Callable[[], str | None] = resolve_one_mcp_executable):
        self._root = root
        self._pack = pack
        self._run = run
        self._windows = windows
        self._mcp_binary = mcp_binary

    @property
    def root(self) -> Path:
        return self._root or install_root() / "mcp-tunnel"

    def _env_file(self) -> Path:
        return self.root / "config" / "gateway.env"

    def _token(self) -> str | None:
        token = load_dot_env(self._env_file()).get("GATEWAY_BEARER_TOKEN")
        return token if token and token != "replace-me" and len(token) >= 16 else None

    def ensure_installed(self) -> Path:
        pack = self._pack or resources_dir() / "mcp-tunnel"
        if not (pack / "gateway" / "server.js").is_file():
            raise PcFeatureError("The Remote MCP pack is missing from this install. Reinstall Cyclone.", "PACK_MISSING", 503)
        root = self.root
        if pack.resolve() != root.resolve():
            _copy_pack(pack, root)
        (root / "artifacts" / "runtime").mkdir(parents=True, exist_ok=True)
        (root / "config").mkdir(parents=True, exist_ok=True)
        (root / "BUNDLE_VERSION").write_text(BUNDLE_VERSION, encoding="utf-8")
        return root

    def _script(self, name: str, args: list[str], timeout: float, with_mcp: bool = True) -> dict[str, Any]:
        if not self._windows():
            raise PcFeatureError("Remote MCP runs on Windows.", "UNSUPPORTED_PLATFORM", 501)
        root = self.ensure_installed()
        script = root / "scripts" / name
        if not script.is_file():
            raise PcFeatureError(f"The Remote MCP pack is missing {name}. Reinstall Cyclone.", "PACK_MISSING", 503)
        env = {"CYCLONE_MCP_TUNNEL_ROOT": str(root)}
        mcp = self._mcp_binary() if with_mcp else None
        if mcp:
            env["MCP_COMMAND"] = mcp
        result = self._run(powershell_argv(script, ["-Json", *args]), env, root, timeout)
        return script_json(result, name, [self._token()])

    def _with_defaults(self, value: dict[str, Any]) -> dict[str, Any]:
        value.setdefault("ok", True)
        value.setdefault("localMcpUrl", LOCAL_MCP_URL)
        value.setdefault("localHealthUrl", LOCAL_HEALTH_URL)
        value.setdefault("installPath", str(self.root))
        value.setdefault("grokStdioUntouched", True)
        value.pop("token", None)
        value.pop("bearer", None)
        return value

    def stopped(self, message: str) -> dict[str, Any]:
        return self._with_defaults({"state": "stopped", "mode": "readonly", "tokenLast4": None, "publicUrl": None,
                                    "mcpUrl": None, "gatewayAlive": False, "cloudflaredAlive": False, "healthOk": False,
                                    "message": message})

    def status(self) -> dict[str, Any]:
        if not self._windows():
            return self.stopped("Remote MCP runs on Windows.")
        try:
            return self._with_defaults(self._script("status-tunnel.ps1", [], 20))
        except PcFeatureError as exc:
            if exc.code == "PACK_MISSING":
                return self.stopped(str(exc))
            raise

    def start(self, mode: str | None = None) -> dict[str, Any]:
        args = []
        if mode:
            if mode not in MODES:
                raise PcFeatureError("Mode must be readonly or full.", "INVALID_REQUEST", 422)
            args = ["-Mode", mode]
        return self._with_defaults(self._script("start-tunnel.ps1", args, 90))

    def stop(self) -> dict[str, Any]:
        return self._with_defaults(self._script("stop-tunnel.ps1", [], 30, with_mcp=False))

    def restart(self, mode: str | None = None) -> dict[str, Any]:
        self.stop()
        return self.start(mode)

    def rotate(self) -> dict[str, Any]:
        return self._with_defaults(self._script("rotate-token.ps1", [], 120))

    def set_mode(self, mode: str) -> dict[str, Any]:
        if mode not in MODES:
            raise PcFeatureError("Mode must be readonly or full.", "INVALID_REQUEST", 422)
        self.ensure_installed()
        set_env_key(self._env_file(), "GATEWAY_MODE", mode)
        status = self.status()
        if status.get("state") in ("running", "degraded"):
            return self.restart(mode)
        return status

    def smoke(self) -> dict[str, Any]:
        return self._with_defaults(self._script("smoke-gateway.ps1", [], 60, with_mcp=False))

    def token(self) -> dict[str, str]:
        """The bearer, only because the owner pressed Show token: they paste it into ChatGPT's connector."""
        self.ensure_installed()
        token = self._token()
        if token is None:
            raise PcFeatureError("There is no token yet: start the tunnel once.", "NO_TOKEN", 404)
        return {"token": token, "last4": token[-4:]}

    def docs(self) -> dict[str, str]:
        root = self.ensure_installed()
        path = root / "docs" / "CONNECTOR_SETUP.md"
        try:
            return {"markdown": path.read_text(encoding="utf-8")[:60_000]}
        except OSError as exc:
            raise PcFeatureError("The connector setup notes are missing from the pack.", "PACK_MISSING", 503) from exc


def protect_env_file(path: Path) -> None:
    """Only the owner may read the tunnel's gateway.env (it holds the bearer)."""
    if os.name == "nt":
        user, domain = os.getenv("USERNAME"), os.getenv("USERDOMAIN")
        if user and domain:
            import subprocess

            subprocess.run(["icacls", str(path), "/inheritance:r", "/grant:r", f"{domain}\\{user}:(R,W)"],
                           capture_output=True, creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
    else:
        try:
            path.chmod(0o600)
        except OSError:
            pass
