_s=open('worm2.py').read(); exec(_s[:_s.rindex('if __name__')])
import os,sys
RES=sys.argv[1]
P=dict(a_rim=35,a_in=18,tau=1.2)
def apath(g,tol):
    g=g.simplify(tol)
    polys=list(g.geoms) if isinstance(g,MultiPolygon) else [g]
    out=[]
    for pg in polys:
        for r in [pg.exterior,*pg.interiors]:
            c=list(r.coords)[:-1]
            out.append('M'+' '.join(f'{x+100:.1f},{y+100:.1f}' for x,y in c)+'Z')
    return ''.join(out)
COLOR=apath(worm(S=math.log(90/6),g=0.08,**P),0.06)
MONO=apath(worm(S=math.log(90/20),g=0.10,**P),0.08)
print('color path chars',len(COLOR),'mono',len(MONO))
HDR='<vector xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt"'
def radial(cx,cy,r,stops):
    items=''.join(f'<item android:offset="{o}" android:color="{c}"/>' for o,c in stops)
    return f'<aapt:attr name="android:fillColor"><gradient android:type="radial" android:centerX="{cx}" android:centerY="{cy}" android:gradientRadius="{r}">{items}</gradient></aapt:attr>'
def linear(x1,y1,x2,y2,stops):
    items=''.join(f'<item android:offset="{o}" android:color="{c}"/>' for o,c in stops)
    return f'<aapt:attr name="android:fillColor"><gradient android:type="linear" android:startX="{x1}" android:startY="{y1}" android:endX="{x2}" android:endY="{y2}">{items}</gradient></aapt:attr>'
VOIDG=radial(100,100,52,[(0,'#FF000405'),(0.35,'#FF011012'),(0.7,'#E60A4D50'),(1,'#001C9E98')])
PETAL=radial(100,100,91,[(0,'#FF000405'),(0.1,'#FF021316'),(0.3,'#FF0B5458'),(0.58,'#FF2EC2B9'),(0.78,'#FF5BE3D6'),(1,'#FF2AA9A3')])
SHEENG=linear(25,18,175,182,[(0,'#47FFFFFF'),(0.45,'#00FFFFFF'),(0.62,'#00000000'),(1,'#4D001214')])
CIRCLE='M100,48 A52,52 0 1,1 99.99,48 Z'
def colour_paths():
    return (f'<path android:pathData="{CIRCLE}">{VOIDG}</path>'
            f'<path android:pathData="{COLOR}" android:fillType="evenOdd">{PETAL}</path>'
            f'<path android:pathData="{COLOR}" android:fillType="evenOdd">{SHEENG}</path>')
def w(rel,text):
    p=os.path.join(RES,rel); os.makedirs(os.path.dirname(p),exist_ok=True); open(p,'w').write(text+'\n')
NOTE='<!-- Cyclone mark (brand/logo-wormhole): seven petals spiralling into the void. Generated by brand/logo-wormhole/src/android.py; do not edit by hand. -->\n'
# 1) in-app colour mark
w('drawable/ic_cyclone_mark_42.xml',NOTE+f'{HDR} android:width="48dp" android:height="48dp" android:viewportWidth="200" android:viewportHeight="200">{colour_paths()}</vector>')
# 2) one-colour status / notification / tile icon
w('drawable/ic_cyclone_status.xml',NOTE+f'{HDR} android:width="24dp" android:height="24dp" android:viewportWidth="200" android:viewportHeight="200"><path android:fillColor="#FFFFFFFF" android:fillType="evenOdd" android:pathData="{MONO}"/></vector>')
# 3) adaptive launcher icon: 108dp canvas, mark 54dp wide (inside the 66dp safe zone)
s=54/180; t=54-100*s
G=f'<group android:scaleX="{s:.5f}" android:scaleY="{s:.5f}" android:translateX="{t:.4f}" android:translateY="{t:.4f}">'
w('drawable/ic_launcher_foreground.xml',NOTE+f'{HDR} android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">{G}{colour_paths()}</group></vector>')
w('drawable/ic_launcher_monochrome.xml',NOTE+f'{HDR} android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">{G}<path android:fillColor="#FFFFFFFF" android:fillType="evenOdd" android:pathData="{MONO}"/></group></vector>')
w('drawable/ic_launcher_background.xml',NOTE+f'{HDR} android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108"><path android:pathData="M0,0h108v108h-108z">{linear(0,0,108,108,[(0,"#FF0A2E34"),(1,"#FF031114")])}</path></vector>')
AD='<?xml version="1.0" encoding="utf-8"?>\n<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n    <background android:drawable="@drawable/ic_launcher_background" />\n    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n</adaptive-icon>'
w('mipmap-anydpi/ic_launcher.xml',AD); w('mipmap-anydpi/ic_launcher_round.xml',AD)
print('written')
