_s=open('worm2.py').read(); exec(_s[:_s.rindex('if __name__')])
import sys,urllib.parse
P=dict(a_rim=35,a_in=18,tau=1.2)
def spath(g,tol,dec=1):
    g=g.simplify(tol); polys=list(g.geoms) if isinstance(g,MultiPolygon) else [g]; out=''
    for pg in polys:
        for r in [pg.exterior,*pg.interiors]:
            c=list(r.coords)[:-1]; out+='M'+'L'.join(f'{x+100:.{dec}f} {y+100:.{dec}f}' for x,y in c)+'Z'
    return out
PET=spath(worm(S=math.log(90/6),g=0.08,**P),0.12)
FAV=spath(worm(S=math.log(90/12),g=0.09,**P),0.35,0)
ts=f'''/**
 * The Cyclone mark (brand/logo-wormhole): seven petals split through the rim, spiralling exponentially smaller into a
 * void. Geometry on a 200 x 200 grid, generated by brand/logo-wormhole/src/glass.py; do not edit by hand.
 */
export const CYCLONE_PETALS = "{PET}";
'''
open(sys.argv[1],'w').write(ts)
fav=f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200"><defs><linearGradient id="t" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#0A2E34"/><stop offset="1" stop-color="#031114"/></linearGradient><radialGradient id="p" gradientUnits="userSpaceOnUse" cx="100" cy="100" r="91"><stop offset="0" stop-color="#000405"/><stop offset=".3" stop-color="#0B5458"/><stop offset=".58" stop-color="#2EC2B9"/><stop offset=".78" stop-color="#5BE3D6"/><stop offset="1" stop-color="#2AA9A3"/></radialGradient></defs><rect width="200" height="200" rx="48" fill="url(#t)"/><g transform="translate(100 100) scale(.82) translate(-100 -100)"><path fill="url(#p)" fill-rule="evenodd" d="{FAV}"/></g></svg>'
open(sys.argv[2],'w').write('data:image/svg+xml,'+urllib.parse.quote(fav,safe=" =:/,.-'"))
print(len(PET),len(fav))
