import test from"node:test";import assert from"node:assert/strict";import{KeyboardCapture}from"../.test-dist/core/keyboardCapture.js";import{keyboardCommandForEvent}from"../.test-dist/core/keyboard.js";import{StreamIsolationRegistry}from"../.test-dist/core/streamIsolation.js";import{MAX_STREAM_RECONNECT_ATTEMPTS,STREAM_FIRST_FRAME_TIMEOUT_MS,STREAM_HANDSHAKE_TIMEOUT_MS,streamCloseIsTerminal}from"../.test-dist/video/webcodecsH264Decoder.js";
import{LivePhoneController}from"../.test-dist/video/livePhoneController.js";
test("keyboard capture starts for exactly one phone and stops",()=>{const c=new KeyboardCapture();c.start("one");assert.equal(c.activeDeviceId(),"one");assert.equal(c.isActiveFor("two"),false);c.start("two");assert.equal(c.activeDeviceId(),"two");c.stop();assert.equal(c.activeDeviceId(),null)});
test("typing is ephemeral and Escape stops capture",()=>{assert.deepEqual(keyboardCommandForEvent({key:"a"}),{type:"text",text:"a"});assert.deepEqual(keyboardCommandForEvent({key:"Escape"}),{type:"stop"})});
test("Ctrl shortcuts are consumed and keyboard capture has no history",()=>{assert.deepEqual(keyboardCommandForEvent({key:"r",ctrlKey:true}),{type:"consume"});const capture=new KeyboardCapture();assert.equal("history" in capture,false);assert.equal("keys" in capture,false)});
test("one broken stream is isolated from other phone streams",()=>{const r=new StreamIsolationRegistry();r.set("one","LIVE");r.set("two","STREAM_ERROR");assert.equal(r.get("one"),"LIVE");assert.equal(r.get("two"),"STREAM_ERROR");assert.equal(r.snapshot().size,2)});
test("stream reconnect is bounded and auth or pairing closes are terminal",()=>{assert.equal(MAX_STREAM_RECONNECT_ATTEMPTS,6);assert.equal(streamCloseIsTerminal(4401),true);assert.equal(streamCloseIsTerminal(4404),true);assert.equal(streamCloseIsTerminal(1006),false)});
test("stream health deadlines expose a stuck open socket instead of reconnecting forever",()=>{assert.equal(STREAM_HANDSHAKE_TIMEOUT_MS,8000);assert.equal(STREAM_FIRST_FRAME_TIMEOUT_MS,12000)});
test("real stream starts even when the fleet snapshot is disconnected and wake health is pending",async()=>{let started=0,wakes=0;const service={mode:"real",sendControl:async(_id,action)=>{if(action.type==="wake")wakes++;return{ok:true,deviceId:"phone"}},reportStreamDiagnostic:async()=>{},getVideoUrl:()=>"ws://127.0.0.1/video",getVideoProtocols:()=>[],getFallbackFrameUrl:()=>""};const device={id:"phone",name:"Pixel",state:"DISCONNECTED",paired:true,connectionLabel:"Reconnecting",lastSeenEpochMs:0,video:{mode:"SCREENSHOT",width:1080,height:2400,rotationDegrees:0},capabilities:{keyboard:true,clipboard:true,clipboardSync:false,reconnect:true}};const renderer={start(){started++},stop(){}};const controller=new LivePhoneController(service,device,"focus",{container:{},canvas:{},fallbackImage:{}},()=>{},()=>{},()=>renderer);controller.start();await Promise.resolve();assert.equal(started,1);assert.equal(wakes,1);controller.stop()});
