package com.cyclone.teamworksniper.ui

import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.cyclone.teamworksniper.UiState
import com.cyclone.teamworksniper.data.*
import java.time.DayOfWeek
import java.time.LocalDate
import java.util.UUID

private enum class DraftMode{ANY,SEQUENCE}
@Composable fun SniperScreen(state:UiState,onSettings:(SniperSettings)->Unit,onRules:(List<ShiftRule>)->Unit,onNotification:()->Unit,onAccessibility:()->Unit,onEvaluate:()->Unit){MaterialTheme{Surface(Modifier.fillMaxSize()){LazyColumn(contentPadding=PaddingValues(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{Column{Text("Teamwork Sniper",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Bold);Text(when{!state.permissions.notificationAccess->"MISSING NOTIFICATION ACCESS";!state.permissions.accessibilityAccess->"MISSING ACCESSIBILITY ACCESS";!state.settings.enabled->"DISABLED";state.settings.armed->"ARMED";else->"READY · DISARMED"});Text("Semantic Teamwork shift matching only")}};item{Card{Column(Modifier.padding(16.dp)){Text("Permissions",fontWeight=FontWeight.Bold);PermissionRow("Notification access",state.permissions.notificationAccess,onNotification);PermissionRow("Accessibility access",state.permissions.accessibilityAccess,onAccessibility)}}};item{Card{Column(Modifier.padding(16.dp)){Toggle("Sniper enabled","Allows trigger processing and evaluation",state.settings.enabled){onSettings(state.settings.copy(enabled=it))};Toggle("Armed","Only this state permits claim actions",state.settings.armed){onSettings(state.settings.copy(armed=it))};if(!state.settings.armed)Text("Disarmed mode still reads and logs what WOULD happen.",style=MaterialTheme.typography.bodySmall)}}};item{RuleComposer(state.rules,onRules)};if(state.rules.isNotEmpty()){item{Text("Desired rules",fontWeight=FontWeight.Bold)};items(state.rules,key={it.id}){r->Card{Row(Modifier.padding(12.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(r.name,fontWeight=FontWeight.SemiBold);Text(r.type.name,style=MaterialTheme.typography.bodySmall)};Switch(r.enabled,{v->onRules(state.rules.map{if(it.id==r.id)it.copy(enabled=v)else it})});TextButton({onRules(state.rules.filterNot{it.id==r.id})}){Text("Delete")}}}}};item{Button(onEvaluate,Modifier.fillMaxWidth(),enabled=state.permissions.accessibilityAccess){Text("Evaluate Teamwork now")}};item{Text("Recent activity",fontWeight=FontWeight.Bold)};items(state.activity.take(12),key={it.id}){a->Card{Column(Modifier.padding(12.dp)){Text("${a.triggerSource} · ${a.decision}",fontWeight=FontWeight.SemiBold);Text("Armed ${a.armedState} · attempted ${a.claimAttempted}",style=MaterialTheme.typography.bodySmall);a.firstComparisonLatencyMs?.let{Text("First comparison ${it}ms",style=MaterialTheme.typography.bodySmall)};if(a.openShifts.isNotEmpty())Text("Open: ${a.openShifts.joinToString()}",style=MaterialTheme.typography.bodySmall);a.claimResult?.let{Text("Claim: $it",style=MaterialTheme.typography.bodySmall)};a.verificationResult?.let{Text("Verify: $it",style=MaterialTheme.typography.bodySmall)};a.failureReason?.let{Text("Reason: $it",style=MaterialTheme.typography.bodySmall)}}}}}}}}
@Composable private fun PermissionRow(label:String,ok:Boolean,open:()->Unit){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(label);Text(if(ok)"Enabled" else "Required",style=MaterialTheme.typography.bodySmall)};OutlinedButton(open){Text(if(ok)"Open" else "Enable")}}}
@Composable private fun Toggle(title:String,subtitle:String,checked:Boolean,onChange:(Boolean)->Unit){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(title,fontWeight=FontWeight.SemiBold);Text(subtitle,style=MaterialTheme.typography.bodySmall)};Switch(checked,onChange)}}
@Composable private fun RuleComposer(existing:List<ShiftRule>,onRules:(List<ShiftRule>)->Unit){var codes by remember{mutableStateOf(emptySet<ShiftCode>())};var mode by remember{mutableStateOf(DraftMode.ANY)};var weeks by remember{mutableStateOf(setOf(0,1))};var days by remember{mutableStateOf(emptySet<DayOfWeek>())};var dates by remember{mutableStateOf(emptySet<LocalDate>())};val ordered=codes.sortedBy{it.order};val validSequence=ordered.size>=2&&ordered.zipWithNext().all{(a,b)->b.order==a.order+1};Card{Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("New desired rule",fontWeight=FontWeight.Bold);Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){ShiftCode.entries.forEach{c->FilterChip(c in codes,{codes=codes.toggle(c)},{Text(c.name)})}};Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){FilterChip(mode==DraftMode.ANY,{mode=DraftMode.ANY},{Text("Claim any selected")});FilterChip(mode==DraftMode.SEQUENCE,{mode=DraftMode.SEQUENCE},{Text("Require full sequence")})};Text(if(mode==DraftMode.ANY)"Selected codes are independent." else "All consecutive codes must be open on the same date.",style=MaterialTheme.typography.bodySmall);Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf(0 to "This week",1 to "+1 week",2 to "+2 weeks").forEach{(w,l)->FilterChip(w in weeks,{weeks=weeks.toggle(w)},{Text(l)})}};Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(6.dp)){DayOfWeek.entries.forEach{d->FilterChip(d in days,{days=days.toggle(d)},{Text(d.name.take(2))})}};Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(6.dp)){(0..13).map{LocalDate.now().plusDays(it.toLong())}.forEach{d->FilterChip(d in dates,{dates=dates.toggle(d)},{Text("${d.dayOfMonth}/${d.monthValue}")})}};val canAdd=codes.isNotEmpty()&&weeks.isNotEmpty()&&(mode==DraftMode.ANY||validSequence);Button({val type=if(mode==DraftMode.SEQUENCE)RuleType.SEQUENCE else if(ordered.size==1)RuleType.EXACT else RuleType.COMBINATION;val sep=if(type==RuleType.SEQUENCE)" → " else " / ";onRules(existing+ShiftRule(UUID.randomUUID().toString(),ordered.joinToString(sep){it.name},type,ordered,true,weeks,dates,days));codes=emptySet();dates=emptySet()},Modifier.fillMaxWidth(),enabled=canAdd){Text("Add rule")}}}}
private fun <T> Set<T>.toggle(v:T)=if(v in this)this-v else this+v
