from __future__ import annotations

from typing import Protocol

from .models import VirtualDeviceConfig, VirtualInstance, VirtualProviderHealth


class VirtualDeviceProvider(Protocol):
    provider_id: str

    def health(self) -> VirtualProviderHealth: ...
    def list_images(self) -> list[dict]: ...
    def create(self, instance: VirtualInstance) -> VirtualInstance: ...
    def start(self, instance: VirtualInstance) -> VirtualInstance: ...
    def stop(self, instance: VirtualInstance) -> VirtualInstance: ...
    def reset(self, instance: VirtualInstance) -> VirtualInstance: ...
    def delete(self, instance: VirtualInstance) -> None: ...
    def configure(self, instance: VirtualInstance, config: VirtualDeviceConfig) -> VirtualInstance: ...
