#Requires -Version 5.1
<#
.SYNOPSIS
  Start the local Cyclone MCP auth gateway and a cloudflared HTTPS tunnel.
.DESCRIPTION
  Does not touch ~/.grok/config.toml. Local Grok Build / Cursor keep using
  CycloneAgentMCP.exe over stdio. This process only fronts a *separate*
  stdio child behind 127.0.0.1:8787 + cloudflared.
#>
[CmdletBinding()]
param(
  [switch]$NoTunnel,
  [string]$Mode,
  [switch]$Json
)

$ErrorActionPreference = "Stop"
$utf8 = New-Object System.Text.UTF8Encoding $false
[Console]::OutputEncoding = $utf8
$OutputEncoding = $utf8
$Root = if ($env:CYCLONE_MCP_TUNNEL_ROOT) { $env:CYCLONE_MCP_TUNNEL_ROOT } else { Split-Path -Parent $PSScriptRoot }
$Runtime = Join-Path $Root "artifacts\runtime"
$ConfigDir = Join-Path $Root "config"
$EnvFile = Join-Path $ConfigDir "gateway.env"
$Node = (Get-Command node -ErrorAction SilentlyContinue).Source
if (-not $Node) { $Node = "C:\Program Files\nodejs\node.exe" }
$Cloudflared = "C:\Program Files (x86)\cloudflared\cloudflared.exe"
$GatewayJs = Join-Path $Root "gateway\server.js"

New-Item -ItemType Directory -Force -Path $Runtime | Out-Null
New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null

function Write-Log([string]$Message) {
  $line = "{0} {1}" -f (Get-Date -Format "yyyy-MM-ddTHH:mm:ssK"), $Message
  Add-Content -Path (Join-Path $Runtime "start-tunnel.log") -Value $line
  if (-not $Json) { Write-Host $line }
}

function Emit-Json($Object) {
  $Object | ConvertTo-Json -Compress -Depth 8
}

function Fail-Json([string]$Message, [string]$State = "stopped") {
  if ($Json) {
    Emit-Json @{
      ok                 = $false
      state              = $State
      error              = $Message
      message            = $Message
      grokStdioUntouched = $true
      installPath        = $Root
    }
    exit 1
  }
  throw $Message
}

function Protect-File([string]$Path) {
  if (-not (Test-Path $Path)) { return }
  $user = "$env:USERDOMAIN\$env:USERNAME"
  icacls $Path /inheritance:r /grant:r "${user}:(R,W)" | Out-Null
}

function Get-EnvValue([string]$Key) {
  if (-not (Test-Path $EnvFile)) { return $null }
  $line = Get-Content $EnvFile | Where-Object { $_ -match ("^" + [regex]::Escape($Key) + "=") } | Select-Object -First 1
  if (-not $line) { return $null }
  return ($line -split '=', 2)[1].Trim()
}

function Set-EnvValue([string]$Key, [string]$Value) {
  $lines = @()
  if (Test-Path $EnvFile) { $lines = @(Get-Content $EnvFile) }
  $found = $false
  $next = foreach ($line in $lines) {
    if ($line -match ("^" + [regex]::Escape($Key) + "=")) {
      $found = $true
      "$Key=$Value"
    } else {
      $line
    }
  }
  if (-not $found) { $next = @($next) + "$Key=$Value" }
  $next | Set-Content -Path $EnvFile -Encoding ascii
  Protect-File $EnvFile
}

function Resolve-McpBinary {
  $candidates = @(
    $env:MCP_COMMAND,
    (Get-EnvValue "MCP_COMMAND"),
    (Join-Path $env:LOCALAPPDATA "Cyclone One\CycloneAgentMCP.exe"),
    (Join-Path $env:LOCALAPPDATA "Cyclone PC Companion\CycloneAgentMCP.exe")
  ) | Where-Object { $_ }
  foreach ($c in $candidates) {
    if ($c -and (Test-Path $c)) { return $c }
  }
  if ($candidates.Count -gt 0) { return $candidates[0] }
  return (Join-Path $env:LOCALAPPDATA "Cyclone One\CycloneAgentMCP.exe")
}

function Get-OrCreateToken {
  $tok = Get-EnvValue "GATEWAY_BEARER_TOKEN"
  if ($tok -and $tok -ne "replace-me" -and $tok.Length -ge 16) { return $tok }
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  $bytes = New-Object byte[] 32
  $rng.GetBytes($bytes)
  $tok = [Convert]::ToBase64String($bytes).TrimEnd("=").Replace("+", "-").Replace("/", "_")
  $modeValue = if ($Mode) { $Mode } else { "readonly" }
  $mcp = Resolve-McpBinary
  @(
    "# Generated by Cyclone One Settings. Do not commit."
    "GATEWAY_BEARER_TOKEN=$tok"
    "GATEWAY_HOST=127.0.0.1"
    "GATEWAY_PORT=8787"
    "GATEWAY_MODE=$modeValue"
    "MCP_COMMAND=$mcp"
    "MCP_ARGS=serve"
  ) | Set-Content -Path $EnvFile -Encoding ascii
  Protect-File $EnvFile
  Write-Log "generated bearer token in $EnvFile (last4 $($tok.Substring($tok.Length - 4)))"
  return $tok
}

function Stop-PidFile([string]$PidPath, [string]$Name) {
  if (-not (Test-Path $PidPath)) { return }
  $old = (Get-Content $PidPath -ErrorAction SilentlyContinue | Select-Object -First 1)
  if ($old) {
    try {
      $proc = Get-Process -Id ([int]$old) -ErrorAction Stop
      Write-Log "stopping $Name pid=$old"
      Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue
    } catch { }
  }
  Remove-Item $PidPath -Force -ErrorAction SilentlyContinue
}

function Stop-LeftoverListeners {
  Get-CimInstance Win32_Process -ErrorAction SilentlyContinue |
    Where-Object {
      $_.CommandLine -and (
        $_.CommandLine -like "*gateway\server.js*" -or
        $_.CommandLine -like "*gateway/server.js*" -or
        ($_.Name -eq "cloudflared.exe" -and $_.CommandLine -like "*127.0.0.1:8787*")
      )
    } |
    ForEach-Object {
      Write-Log "stopping leftover $($_.Name) pid=$($_.ProcessId)"
      Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue
    }
}

# CreateProcess via WMI so the child outlives this script's job object
# (Grok Build / CI wrappers kill Start-Process descendants on exit).
function Start-Breakaway([string]$CommandLine, [string]$WorkingDirectory) {
  $r = Invoke-CimMethod -ClassName Win32_Process -MethodName Create -Arguments @{
    CommandLine      = $CommandLine
    CurrentDirectory = $WorkingDirectory
  }
  if ($null -eq $r -or $r.ReturnValue -ne 0 -or -not $r.ProcessId) {
    throw "Win32_Process.Create failed ReturnValue=$($r.ReturnValue) cmd=$CommandLine"
  }
  return [int]$r.ProcessId
}

try {
  if (-not (Test-Path $Node)) { Fail-Json "node.exe not found. Install Node 18+ to run the auth gateway." }
  if (-not (Test-Path $GatewayJs)) { Fail-Json "missing $GatewayJs" }
  $Mcp = Resolve-McpBinary
  if (-not (Test-Path $Mcp)) { Fail-Json "missing CycloneAgentMCP.exe at $Mcp. Install Cyclone One first." }
  if (-not $NoTunnel -and -not (Test-Path $Cloudflared)) {
    Fail-Json "cloudflared not found at $Cloudflared"
  }

  $token = Get-OrCreateToken
  $resolvedMode = if ($Mode) { $Mode.ToLowerInvariant() } else { (Get-EnvValue "GATEWAY_MODE") }
  if (-not $resolvedMode) { $resolvedMode = "readonly" }
  if ($resolvedMode -ne "readonly" -and $resolvedMode -ne "full") {
    Fail-Json "invalid GATEWAY_MODE=$resolvedMode (use readonly or full)"
  }
  Set-EnvValue "GATEWAY_MODE" $resolvedMode
  Set-EnvValue "MCP_COMMAND" $Mcp
  Set-EnvValue "MCP_ARGS" "serve"
  Set-EnvValue "GATEWAY_HOST" "127.0.0.1"
  Set-EnvValue "GATEWAY_PORT" "8787"

  Stop-PidFile (Join-Path $Runtime "gateway.pid") "gateway"
  Stop-PidFile (Join-Path $Runtime "cloudflared.pid") "cloudflared"
  Stop-LeftoverListeners
  Start-Sleep -Milliseconds 400

  $gwLog = Join-Path $Runtime "gateway.log"
  $gwErr = Join-Path $Runtime "gateway.err"
  $cfLog = Join-Path $Runtime "cloudflared.log"
  $cfErr = Join-Path $Runtime "cloudflared.err"
  foreach ($f in @($gwLog, $gwErr, $cfLog, $cfErr)) {
    if (Test-Path $f) { Remove-Item $f -Force }
  }

  $env:GATEWAY_LOG_FILE = $gwErr
  $gwCmd = '"{0}" "{1}"' -f $Node, $GatewayJs
  $gwId = Start-Breakaway $gwCmd $Root
  Set-Content -Path (Join-Path $Runtime "gateway.pid") -Value $gwId
  Write-Log "gateway pid=$gwId"

  $healthy = $false
  for ($i = 0; $i -lt 40; $i++) {
    Start-Sleep -Milliseconds 250
    if (-not (Get-Process -Id $gwId -ErrorAction SilentlyContinue)) {
      Fail-Json "gateway exited early. See $gwErr" "degraded"
    }
    try {
      $r = Invoke-WebRequest -Uri "http://127.0.0.1:8787/health" -UseBasicParsing -TimeoutSec 2
      if ($r.StatusCode -eq 200) { $healthy = $true; break }
    } catch { }
  }
  if (-not $healthy) { Fail-Json "gateway did not become healthy on http://127.0.0.1:8787/health" "degraded" }
  Write-Log "gateway healthy on http://127.0.0.1:8787/health"

  $urlFile = Join-Path $Runtime "public-url.txt"
  Remove-Item $urlFile -Force -ErrorAction SilentlyContinue
  $public = $null
  $cfId = $null

  if (-not $NoTunnel) {
    $cfCmd = '"{0}" tunnel --url http://127.0.0.1:8787 --no-autoupdate --protocol http2 --metrics 127.0.0.1:20241 --logfile "{1}"' -f $Cloudflared, $cfErr
    $cfId = Start-Breakaway $cfCmd $Root
    Set-Content -Path (Join-Path $Runtime "cloudflared.pid") -Value $cfId
    Write-Log "cloudflared pid=$cfId"

    for ($i = 0; $i -lt 60; $i++) {
      Start-Sleep -Milliseconds 500
      if (-not (Get-Process -Id $cfId -ErrorAction SilentlyContinue)) {
        Fail-Json "cloudflared exited early. See $cfErr" "degraded"
      }
      foreach ($logFile in @($cfErr, $cfLog)) {
        if (-not (Test-Path $logFile)) { continue }
        $text = Get-Content $logFile -Raw -ErrorAction SilentlyContinue
        if ($text -match 'https://[a-z0-9-]+\.trycloudflare\.com') {
          $public = $Matches[0]
          break
        }
      }
      if ($public) { break }
    }
    if (-not $public) { Fail-Json "cloudflared did not print a trycloudflare.com URL. See $cfErr" "degraded" }
    Set-Content -Path $urlFile -Value $public -Encoding ascii
    Set-EnvValue "PUBLIC_URL" $public
    Write-Log "public URL $public"
    if (-not $Json) {
      Write-Host ""
      Write-Host "MCP URL:  $public/mcp"
      Write-Host "Health:   $public/health"
      Write-Host "Auth:     Authorization: Bearer (see config\gateway.env)"
      Write-Host "Mode:     $resolvedMode"
    }
  } else {
    Write-Log "started gateway only (--NoTunnel)"
    if (-not $Json) {
      Write-Host "Local MCP: http://127.0.0.1:8787/mcp"
      Write-Host "Health:    http://127.0.0.1:8787/health"
    }
  }

  $last4 = $token.Substring($token.Length - 4)
  $state = if ($public) { "running" } elseif ($NoTunnel) { "degraded" } else { "running" }
  $mcpUrl = if ($public) { "$public/mcp" } else { "http://127.0.0.1:8787/mcp" }
  $healthUrl = if ($public) { "$public/health" } else { "http://127.0.0.1:8787/health" }
  if ($Json) {
    Emit-Json @{
      ok                 = $true
      state              = $state
      mode               = $resolvedMode
      tokenLast4         = $last4
      publicUrl          = $public
      mcpUrl             = $mcpUrl
      healthUrl          = $healthUrl
      localMcpUrl        = "http://127.0.0.1:8787/mcp"
      localHealthUrl     = "http://127.0.0.1:8787/health"
      gatewayAlive       = $true
      cloudflaredAlive   = [bool]$cfId
      healthOk           = $true
      mcpBinaryOk        = $true
      mcpBinary          = $Mcp
      gatewayPid         = $gwId
      cloudflaredPid     = $cfId
      installPath        = $Root
      grokStdioUntouched = $true
      message            = if ($public) { "Tunnel running. Copy the MCP URL and bearer into ChatGPT / Grok chat connectors." } else { "Gateway running on loopback. Public tunnel was not started." }
    }
  } else {
    Write-Host ("Token file: {0}  (last4 {1})" -f $EnvFile, $last4)
    Write-Host "Stop with:  $Root\scripts\stop-tunnel.ps1"
  }
} catch {
  Fail-Json $_.Exception.Message "stopped"
}
